"""
Directory Listing Detection.

Checks whether common directories on the target return browseable listings
(Apache-style "Index of /", Nginx directory listing, IIS directory browsing).

A public directory listing hands attackers a file inventory: backup archives,
uploaded files, log dumps, and configuration files become trivially discoverable.

Paid equivalents: Nikto -Tuning 3, Acunetix directory traversal checks.
"""

import re
from typing import Any, Dict, List, Tuple
from urllib.parse import urlparse

from tblue.scanner.base import BaseScanner
from tblue.logger import get_logger, log_pass, log_fail, log_warn

logger = get_logger(__name__)

# Common directories to probe for listings
_DIRECTORIES: List[str] = [
    "/uploads/",
    "/upload/",
    "/files/",
    "/file/",
    "/images/",
    "/img/",
    "/media/",
    "/assets/",
    "/static/",
    "/backup/",
    "/backups/",
    "/bak/",
    "/logs/",
    "/log/",
    "/tmp/",
    "/temp/",
    "/cache/",
    "/old/",
    "/archive/",
    "/archives/",
    "/data/",
    "/db/",
    "/database/",
    "/exports/",
    "/export/",
    "/downloads/",
    "/download/",
    "/attachments/",
    "/documents/",
    "/docs/",
    "/storage/",
    "/content/",
    "/private/",
    "/public/",
    "/admin/files/",
    "/admin/uploads/",
    "/wp-content/uploads/",
    "/wp-content/backup/",
    "/sites/default/files/",      # Drupal
    "/user/",
    "/users/",
    "/.git/",
    "/.svn/",
    "/.hg/",
]

# Patterns that indicate a directory listing page
_LISTING_PATTERNS: List[re.Pattern] = [
    re.compile(r"Index of /",              re.I),
    re.compile(r"<title>Index of",         re.I),
    re.compile(r"\[To Parent Directory\]", re.I),
    re.compile(r"Directory listing for",   re.I),
    re.compile(r"Parent Directory</a>",    re.I),
    re.compile(r"<h1>Directory: /",        re.I),
    re.compile(r"<title>Directory listing", re.I),
    re.compile(r"<!-- Directory listing generated by", re.I),
    re.compile(r'href="\.\."',             re.I),  # generic ../ link
]

# Patterns suggesting VCS directory exposure (special-cased as FAIL)
_VCS_DIRS = {"/.git/", "/.svn/", "/.hg/"}


class DirectoryListingScanner(BaseScanner):
    """Probe common directories for publicly accessible listings."""

    def scan(self, url: str) -> List[Dict[str, Any]]:
        self.results = []
        base = _base_url(url)
        exposed: List[Tuple[str, bool]] = []  # (path, is_vcs)

        for directory in _DIRECTORIES:
            probe_url = base + directory
            try:
                resp = self.http.get(probe_url)
                if not resp or resp.status_code != 200:
                    continue
                body = resp.text or ""
                if _is_listing(body):
                    is_vcs = directory in _VCS_DIRS
                    exposed.append((probe_url, is_vcs))
                    if is_vcs:
                        log_fail(logger, f"VCS directory listing exposed: {probe_url}")
                        self.results.append(self._result(
                            url, f"Directory listing — VCS directory exposed ({directory.strip('/')})", "FAIL",
                            detail=(
                                f"The directory {probe_url} is publicly accessible and appears to be "
                                "a version-control directory. This exposes your full source code history. "
                                "Fix: immediately block access to /.git/, /.svn/, /.hg/ at the web server "
                                "or load balancer level, and rotate any secrets that may have been committed."
                            )
                        ))
                    else:
                        log_warn(logger, f"Directory listing enabled: {probe_url}")
                        self.results.append(self._result(
                            url, f"Directory listing — exposed ({directory.strip('/')})", "WARN",
                            detail=(
                                f"Directory listing is enabled at {probe_url}. "
                                "This allows enumeration of all files in the directory, potentially "
                                "exposing backups, logs, uploads, or other sensitive files. "
                                "Fix: disable directory listing (Apache: Options -Indexes; "
                                "Nginx: remove autoindex on; IIS: disable Directory Browsing)."
                            )
                        ))
            except Exception:
                continue

        if not exposed:
            log_pass(logger, f"No directory listings found on {url}")
            self.results.append(self._result(
                url, "Directory listing — none exposed", "PASS",
                detail=(
                    f"None of the {len(_DIRECTORIES)} probed directories returned a "
                    "publicly accessible directory listing."
                )
            ))

        return self.results


def _is_listing(body: str) -> bool:
    """Return True if the response body looks like a directory listing."""
    return any(p.search(body) for p in _LISTING_PATTERNS)


def _base_url(url: str) -> str:
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}"
