"""
Source Map File Exposure Scanner.

JavaScript source maps (.map files) are generated by build tools (webpack,
Parcel, esbuild, Rollup, Vite) to map minified production code back to
original source for debugging. When exposed in production, they reveal:

- Full original TypeScript/ES6 source code
- Internal file paths and directory structure
- Business logic and algorithm implementations
- Comments, TODO notes, and developer notes
- Hardcoded values, internal API endpoints, and auth logic
- npm package names and versions (secondary dependency enumeration)

Format: JSON with `sources`, `sourcesContent`, `mappings`, `sourceRoot` keys.
Enabled in bundles via: `//# sourceMappingURL=app.js.map`

Detection approach (passive, read-only):
1. Find JavaScript bundle files from page <script> tags
2. Check each JS file for `//# sourceMappingURL=` directive
3. Probe for `.map` files (bundle.js → bundle.js.map)
4. Validate map file content (must contain `sources` and `mappings` keys)
5. Warn if map contains `sourcesContent` (original source included inline)
6. Check for loose map files in common locations (/static/js/, /dist/, /build/)
7. Detect exposed webpack stats.json (lists all bundle dependencies and paths)

Professional equivalents: Detectify "Source Map Exposure" scanner,
Acunetix "JavaScript Source Maps Exposed", StackHawk "Source Map Detection".

CWE-540: Inclusion of Sensitive Information in Source Code
CWE-200: Exposure of Sensitive Information to an Unauthorized Actor
OWASP A05:2021 — Security Misconfiguration
"""

import re
import json
from typing import Any, Dict, List
from urllib.parse import urlparse, urljoin

from bs4 import BeautifulSoup

from tblue.scanner.base import BaseScanner
from tblue.logger import get_logger, log_pass, log_fail, log_warn

logger = get_logger(__name__)

# Sourcemap directive in JavaScript files
_SOURCEMAP_URL_RE = re.compile(
    r"//[#@]\s*sourceMappingURL\s*=\s*([^\s\r\n]+)",
    re.I,
)

# Loose sourcemap directive (X-SourceMap header or DataURL)
_DATA_URI_MAP_RE = re.compile(
    r"//[#@]\s*sourceMappingURL\s*=\s*data:application/json",
    re.I,
)

# JS bundle filename patterns (webpack/Parcel/Vite typical names)
_BUNDLE_NAME_RE = re.compile(
    r'(?:^|/)((?:main|app|bundle|vendor|chunk|index|runtime|polyfill|'
    r'[a-f0-9]{8,16})\.[a-z0-9]+(?:\.[a-f0-9]{8,16})?\.js)(?:\?|$)',
    re.I,
)

# Source map file validation
_MAP_SOURCES_RE = re.compile(r'"sources"\s*:', re.I)
_MAP_MAPPINGS_RE = re.compile(r'"mappings"\s*:', re.I)
_MAP_SOURCES_CONTENT_RE = re.compile(r'"sourcesContent"\s*:', re.I)
_MAP_SOURCE_ROOT_RE = re.compile(r'"sourceRoot"\s*:\s*"([^"]+)"', re.I)

# Internal path exposure in source root
_INTERNAL_PATH_RE = re.compile(
    r'(?:/home/|/Users/|/var/|/srv/|/opt/|C:\\|D:\\|/root/|/build/|'
    r'/workspace/|/jenkins/|/ci/|/drone/|/github/workspace)',
    re.I,
)

# webpack stats.json — exposes all chunks, asset sizes, module IDs
_STATS_PATHS = [
    "/stats.json",
    "/webpack-stats.json",
    "/build/stats.json",
    "/dist/stats.json",
    "/static/stats.json",
]

# Common webpack/Parcel/Vite output directories
_BUNDLE_DIRS = [
    "/static/js/",
    "/assets/js/",
    "/dist/js/",
    "/build/js/",
    "/dist/",
    "/build/",
    "/public/js/",
    "/js/",
]

# Common bundle names to probe
_COMMON_BUNDLE_NAMES = [
    "main.js",
    "app.js",
    "bundle.js",
    "vendor.js",
    "chunk.js",
    "index.js",
    "runtime.js",
]


class SourceMapScanner(BaseScanner):
    """Detect exposed JavaScript source maps and webpack stats files."""

    def scan(self, url: str) -> List[Dict[str, Any]]:
        self.results = []

        resp = self.http.get(url)
        if resp is None:
            self.results.append(self._result(
                url, "Source map — target unreachable", "PASS",
                detail="No response from target."
            ))
            return self.results

        body = resp.text or ""
        parsed = urlparse(url)
        base = f"{parsed.scheme}://{parsed.netloc}"

        found_any = False

        # ── 1. Find JS bundles from page scripts ─────────────────────────────
        found_any |= self._check_page_scripts(url, base, body)

        # ── 2. Probe common bundle paths for map files ────────────────────────
        found_any |= self._probe_common_bundles(url, base)

        # ── 3. Check for webpack stats.json ───────────────────────────────────
        found_any |= self._check_webpack_stats(url, base)

        if not found_any:
            log_pass(logger, f"No exposed source maps detected on {url}")
            self.results.append(self._result(
                url,
                "Source map — no exposed JavaScript source maps detected",
                "PASS",
                detail=(
                    "No .map files or webpack stats.json were found to be publicly accessible. "
                    "Fix: configure your web server to deny access to *.map files; "
                    "use webpack's devtool: 'hidden-source-map' (generates maps for error tracking "
                    "without exposing them publicly); "
                    "or use 'nosources-source-map' to omit original source content."
                )
            ))

        return self.results

    def _check_page_scripts(self, url: str, base: str, body: str) -> bool:
        """Find JS bundles from page scripts and check for source maps."""
        found = False
        try:
            soup = BeautifulSoup(body, "html.parser")
            checked = set()
            for tag in soup.find_all("script", src=True, limit=20):
                src = tag.get("src", "")
                if not src or not src.endswith(".js"):
                    continue
                js_url = src if src.startswith("http") else urljoin(base, src)
                if js_url in checked:
                    continue
                checked.add(js_url)

                # Skip external CDN scripts
                js_parsed = urlparse(js_url)
                if js_parsed.netloc != urlparse(base).netloc:
                    continue

                result = self._check_js_for_map(js_url)
                if result:
                    found = True
        except Exception:
            pass
        return found

    def _check_js_for_map(self, js_url: str) -> bool:
        """Fetch a JS file, check for sourceMappingURL, then probe the map file."""
        try:
            r = self.http.get(js_url)
            if r is None or r.status_code != 200:
                return False
            js_body = r.text or ""

            # Skip data URL source maps (inline, OK)
            if _DATA_URI_MAP_RE.search(js_body):
                return False

            # Check X-SourceMap header
            r_headers = {k.lower(): v for k, v in (r.headers or {}).items()}
            x_sourcemap = r_headers.get("x-sourcemap", "")
            if x_sourcemap:
                return self._probe_map_file(urljoin(js_url, x_sourcemap), js_url)

            # Find inline sourceMappingURL
            m = _SOURCEMAP_URL_RE.search(js_body[-500:])  # usually at end of file
            if not m:
                # No sourcemap directive — try probing for .map file anyway
                map_url = js_url + ".map"
                return self._probe_map_file(map_url, js_url)

            map_ref = m.group(1).strip()
            if map_ref.startswith("data:"):
                return False  # inline map, not exposed

            map_url = map_ref if map_ref.startswith("http") else urljoin(js_url, map_ref)
            return self._probe_map_file(map_url, js_url)

        except Exception:
            return False

    def _probe_map_file(self, map_url: str, source_js_url: str) -> bool:
        """Probe a source map URL and report if it's accessible."""
        try:
            r = self.http.get(map_url)
            if r is None or r.status_code != 200:
                return False

            body = r.text or ""
            if not body or len(body) < 10:
                return False

            # Validate it's actually a source map
            is_map = (_MAP_SOURCES_RE.search(body) and _MAP_MAPPINGS_RE.search(body))
            if not is_map:
                return False

            has_source_content = bool(_MAP_SOURCES_CONTENT_RE.search(body))

            # Check for internal path exposure in sourceRoot
            root_m = _MAP_SOURCE_ROOT_RE.search(body)
            internal_path = ""
            if root_m:
                root = root_m.group(1)
                if _INTERNAL_PATH_RE.search(root):
                    internal_path = root

            if has_source_content:
                log_fail(logger, f"Source map with original source code exposed: {map_url}")
                self.results.append(self._result(
                    map_url,
                    "Source map — JavaScript source map with original source code exposed",
                    "FAIL",
                    detail=(
                        f"The source map {map_url} (for {source_js_url}) is publicly accessible "
                        "and contains `sourcesContent` — the full original TypeScript/ES6/JSX "
                        "source code. Attackers can reconstruct the application logic, find "
                        "hardcoded secrets, discover internal API endpoints, and identify "
                        "vulnerabilities in the original code. "
                        "Fix: configure webpack devtool to 'hidden-source-map' or 'nosources-source-map'; "
                        "block .map files at the web server level "
                        "(Nginx: location ~* \\.map$ { deny all; })."
                    )
                ))
            else:
                log_warn(logger, f"Source map exposed (no source content): {map_url}")
                self.results.append(self._result(
                    map_url,
                    "Source map — JavaScript source map file publicly accessible",
                    "WARN",
                    detail=(
                        f"The source map {map_url} is publicly accessible. "
                        "Even without `sourcesContent`, source maps expose original file paths "
                        "and directory structure, enabling attackers to enumerate source files "
                        "and understand the application architecture. "
                        f"{f'Internal server path exposed in sourceRoot: {internal_path}. ' if internal_path else ''}"
                        "Fix: deny access to .map files in production; "
                        "use 'hidden-source-map' devtool option."
                    )
                ))

            if internal_path and not has_source_content:
                # Also add a separate finding for the path disclosure
                log_warn(logger, f"Internal path exposed in source map sourceRoot: {internal_path}")
                self.results.append(self._result(
                    map_url,
                    "Source map — internal server path exposed in sourceRoot",
                    "WARN",
                    detail=(
                        f"The source map at {map_url} reveals an internal server file path "
                        f"in the `sourceRoot` field: '{internal_path}'. "
                        "This exposes the server's directory structure and can assist attackers "
                        "in path traversal or targeted attacks. "
                        "Fix: set sourceRoot to an empty string or a public URL in webpack config; "
                        "strip absolute paths from production source maps."
                    )
                ))

            return True

        except Exception:
            return False

    def _probe_common_bundles(self, url: str, base: str) -> bool:
        """Probe common webpack bundle paths for exposed map files."""
        found = False
        for bundle_dir in _BUNDLE_DIRS[:4]:  # limit dirs
            for bundle_name in _COMMON_BUNDLE_NAMES[:3]:  # limit names
                map_url = base + bundle_dir + bundle_name + ".map"
                try:
                    r = self.http.get(map_url)
                    if r is None or r.status_code != 200:
                        continue
                    body = r.text or ""
                    if (_MAP_SOURCES_RE.search(body) and _MAP_MAPPINGS_RE.search(body)):
                        js_url = base + bundle_dir + bundle_name
                        if self._probe_map_file(map_url, js_url):
                            found = True
                            return found  # one finding is enough
                except Exception:
                    continue
        return found

    def _check_webpack_stats(self, url: str, base: str) -> bool:
        """Check for exposed webpack stats.json file."""
        for stats_path in _STATS_PATHS:
            stats_url = base + stats_path
            try:
                r = self.http.get(stats_url)
                if r is None or r.status_code != 200:
                    continue
                body = r.text or ""
                if not body:
                    continue

                # Validate webpack stats.json content
                try:
                    data = json.loads(body)
                    if isinstance(data, dict) and any(
                        k in data for k in ("chunks", "modules", "assets", "entrypoints")
                    ):
                        log_fail(logger, f"webpack stats.json exposed: {stats_url}")
                        self.results.append(self._result(
                            stats_url,
                            "Source map — webpack stats.json publicly accessible",
                            "FAIL",
                            detail=(
                                f"The webpack stats.json file is accessible at {stats_url}. "
                                "This file reveals all JavaScript chunks, module IDs, asset sizes, "
                                "source file paths, npm dependencies, and the complete module "
                                "dependency graph of the application. "
                                "Attackers use this to enumerate the entire JavaScript codebase "
                                "structure without needing to reverse-engineer minified code. "
                                "Fix: never deploy stats.json to production; "
                                "add stats.json to .gitignore and web server deny rules."
                            )
                        ))
                        return True
                except (json.JSONDecodeError, ValueError):
                    # Not valid JSON
                    if '"chunks"' in body and '"modules"' in body:
                        log_warn(logger, f"webpack stats-like file found: {stats_url}")
                        self.results.append(self._result(
                            stats_url,
                            "Source map — webpack stats-like file found",
                            "WARN",
                            detail=(
                                f"A file with webpack stats-like content is accessible at {stats_url}. "
                                "Fix: remove stats files from production deployments."
                            )
                        ))
                        return True
            except Exception:
                continue
        return False
